window.stores = {
	"1" : "OzPlaza",
	"2" : "SOS",
	"4": "Idirect",
	//"5": "Microsoft",
	"6": "SPWarehouse",
	"7": "Kobayashi",
	"8": "Hobbyco",
	"9": "Habotania eBay",
	//"11": "Groupon",
	//"12": "Mydeal",
	"16": 'Sons of Amazon',
	"21": "new Store",
	"31": "Kitncaboodle",
	"32": "PackingSorted",
	"33": "Roofstuff",
	/*"34": "ANKAMe",*/
	"35": "CleanHQ",
	"36": "Evo Build",
	"37": "BH&G",
	"41": "Amazon",
	"51": "Magento-Emega",
	"61": "Charli Chair",
	"62": "Habitania",
	"71": "Hobbyco Website",
	"81": "B2B-Wholesale",
	"82": "B2B-Transfer",
	"91": "Hobbyco Catch",
	"93": "Emega Catch",
	"105": "Spartan",
}